server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: analysis
          uri: lb://analysis
          predicates:
            - Path=/analysis/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
